name: 'Github Tag Action'
description: 'generate tags'
author: 'pxpm'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  tag:
    description: 'Tag text'
    default: '0.1.0'
  commit-sha:
    description: optional commit sha to apply the tag to

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
